### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Kqmu** [Thelnfamous1/Dungeons-Gear#116]
**Console:** 
[06.08 23:59:50] [Server] java.lang.NullPointerException
[06.08 23:59:50] [Server] 	at com.infamous.dungeons_gear.enchantments.melee_ranged.EnigmaResonatorEnchantment.onVanillaNonCriticalHit(EnigmaResonatorEnchantment.java:45)
[06.08 23:59:50] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler_484_EnigmaResonatorEnchantment_onVanillaNonCriticalHit_CriticalHitEvent.invoke(.dynamic)
[06.08 23:59:50] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[06.08 23:59:50] [Server] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[06.08 23:59:50] [Server] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[06.08 23:59:50] [Server] 	at net.minecraftforge.common.ForgeHooks.getCriticalHit(ForgeHooks.java:1050)
[06.08 23:59:50] [Server] 	at net.minecraft.entity.player.PlayerEntity.func_71059_n(PlayerEntity.java:1072)
[06.08 23:59:50] [Server] 	at net.minecraft.entity.player.ServerPlayerEntity.func_71059_n(ServerPlayerEntity.java:1292)
[06.08 23:59:50] [Server] 	at net.minecraft.network.play.ServerPlayNetHandler.func_147340_a(ServerPlayNetHandler.java:1205)
[06.08 23:59:50] [Server] 	at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:74)
[06.08 23:59:50] [Server] 	at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:13)
[06.08 23:59:50] [Server] 	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
[06.08 23:59:50] [Server] 	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[06.08 23:59:50] [Server] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
[06.08 23:59:50] [Server] 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)

**Modlist:**
[07.08 00:04:51] [Server] [main/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, BetterDungeons-1.16.4-1.1.jar, NetherPortalFix_1.16.3-7.2.1.jar, zombiehorsespawn_1.16.5-3.0.jar, Industrial Agriculture[Core]-1.16.5-1.8.11.jar, findme-1.16.3-2.2.0.0.jar, BetterCaves-Forge-1.16.4-1.1.2.jar, ForgeEndertech-1.16.5-7.2.0.0-build.0177.jar, Placebo-1.16.4-4.5.0.jar, citadel-1.7.2-1.16.5.jar, alexsmobs-1.11.1.jar, farmersdelightintegrations-1.16.5-1.1.jar, YungsApi-1.16.4-Forge-12.jar, ibarnoriginsaddon-1.0.4-forge-1.16.5.jar, Bookshelf-Forge-1.16.5-10.2.27.jar, sophisticatedbackpacks-1.16.5-3.0.3.297.jar, guardvillagers-1.16.5.1.2.5.jar, randompatches-2.4.4-forge.jar, Apotheosis-1.16.4-4.6.1.jar, MekanismGenerators-1.16.5-10.0.21.448.jar, dynviewdist-2.0.jar, JustEnoughResources-1.16.5-0.12.1.127.jar, huskspawn_1.16.5-1.4.jar, mob_grinding_utils-1.16.5-0.4.23.jar, betterendforge-1.16.4-1.6.0.jar, Industrial Agriculture[Botania]-1.16.5-1.7.2.jar, corpse-1.16.5-1.0.5.jar, FarmersDelight-1.16.5-0.4.5.jar, repurposed_structures_forge-3.0.4+1.16.5.jar, morevillagers-FORGE-1.16.5-1.5.4.jar, MekanismAdditions-1.16.5-10.0.21.448.jar, Botania-1.16.5-419.jar, tinkersbettercompat-0.2-1.16.5-36.1.0.jar, villagespawnpoint_1.16.5-1.6.jar, spark-forge.jar, curios-forge-1.16.5-4.0.5.2.jar, Patchouli-1.16.4-53.1.jar, Origins-1.16.5-0.7.3.8-forge.jar, collective-1.16.5-2.46.jar, YungsExtras-Forge-1.16.4-1.0.jar, sylvano-0.1.0.jar, Chunk Pregenerator-V1.16-3.0.5.jar, BetterStrongholds-1.16.4-1.2.1.jar, buildersaddition-1.16.5-20210517a.jar, MekanismTools-1.16.5-10.0.21.448.jar, SpartanWeaponry-1.16.4-2.1.0-beta-4.jar, sapience-1.16.5-1.1.2.jar, Project_MMO-1.16.5-3.62.2.jar, architectury-1.20.28-forge.jar, AI-Improvements-1.16.2-0.3.0.jar, cloth-config-4.11.26-forge.jar, AdChimneys-1.16.5-6.0.12.0-build.0177.jar, BetterBurning-1.16.5-6.0.6.jar, collectionorigins1-1.0.jar, collectionorigins2-1.0.jar, strayspawn_1.16.5-1.4.jar, FastLeafDecay-v25.jar, Babel-1.0.5.jar, JEPB-1.0.0.jar, ServerTabInfo-1.16.4-1.3.3.jar, GameMenuModOption-1.16.4-1.8.jar, BetterMineshafts-Forge-1.16.4-2.0.4.jar, geckolib-forge-1.16.5-3.0.43.jar, dungeons_gear-1.16.5-3.0.17.jar, BetterAdvancements-1.16.5-0.1.1.115.jar, SaveMyStronghold-1.16.4-1.0.jar, QuarkOddities-1.16.3.jar, mowziesmobs-1.5.19.jar, Cucumber-1.16.4-4.1.10.jar, spiders-2.0-1.16.4-1.0.4.jar, NourishedNetherV8.jar, jei-1.16.5-7.7.1.117.jar, Genesis-0.5.1.jar, ComfortableNether4.3.jar, Pehkui-2.2.1+1.16.5-forge.jar, dungeons_mobs-1.16.5-1.0.8.jar, abnormals_core-1.16.5-3.2.0.jar, Mekanism-1.16.5-10.0.21.448.jar, caelus-forge-1.16.5-2.1.3.1.jar, village-employment-1.16.5-1.4.1.jar, curioofundying-forge-1.16.5-5.2.0.0.jar, ars_nouveau-1.16.5-1.20.1.jar, forge-1.16.5-36.2.2-universal.jar, morezombievillagers_1.16.5-1.4.jar, MysticalAgriculture-1.16.5-4.2.1.jar, CraftingTweaks_1.16.5-12.2.1.jar, sakisiil_origins-1.0.jar, endergetic-1.16.4-3.0.0.jar, TConstruct-1.16.5-3.1.1.252.jar, EnchantmentDescriptions-1.16.5-7.0.12.jar, swingthroughgrass-1.16.4-1.5.3.jar, added_origins_forgefabric-V2.0.0.jar, MouseTweaks-2.14-mc1.16.2.jar, flywheel-1.16-0.2.2.jar, create-mc1.16.5_v0.3.2c.jar, SpartanShields-1.16.5-2.1.2.jar, savageandravage-1.16.5-3.1.0.jar, Mantle-1.16.5-1.6.115.jar, diet-forge-1.16.5-0.38.jar, FastWorkbench-1.16.4-4.5.1.jar, polymorph-forge-1.16.5-0.25.jar, AutoRegLib-1.6-49.jar, AkashicTome-1.4-16.jar, Quark-r2.4-316.jar, charm-forge-1.16.5-2.3.2.jar, FastFurnace-1.16.4-4.4.0.jar, nethers_delight-1.1.jar, appleskin-forge-mc1.16.x-2.1.0.jar, byg-1.3.0.jar, Industrial Agriculture[Mekanism]-1.16.3-1.7.1.jar, CosmeticArmorReworked-1.16.5-v4.jar, createaddition-1.16.5-20210801b.jar, pipez-1.16.5-1.2.8.jar, Regrowth-1.16.4-1.16.5-1.35.0.22.jar, supplementaries-1.16.5-0.14.5.jar, selene-1.16.5-1.5.jar, ironchest-1.16.5-11.2.13.jar, AmbientSounds_v3.1.9_mc1.16.5.jar, CreativeCore_v2.2.0_mc1.16.5.jar, charmonium-forge-1.16.5-2.3.2.jar

I think something regarding "com.infamous.dungeons_gear.enchantments.melee_ranged.EnigmaResonatorEnchantment.onVanillaNonCriticalHit(EnigmaResonatorEnchantment.java:45)" I didnt encounter this error in singleplayer but as soon as I loaded it on a server it and I aws fighting Mekanism's baby skeleton blocking arrows etc. mob kills me, and started shooting this error freezing the world into place (not an official crash just everything is frozen)

**Comment by Thelnfamous1** [comment]
@Jackiecrazy NPE isn’t handled when obtaining the souls cap in the Enigma Resonator enchantment’s event handler

**Comment by Patrigan** [comment]
With the move from comboCap to a new capability and with some new attributes, this issue should no longer appear in the most recent beta.
