### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by PiglinSabbath** [Thelnfamous1/Dungeons-Gear#149]
Thread: Render thread
Stacktrace:
	at com.infamous.dungeons_gear.items.VanillaItemModelProperties.<init>(VanillaItemModelProperties.java:17) ~[?:1.16.5-3.1.2-beta] {re:classloading}
-- MOD dungeons_gear --
Details:
	Mod File: dungeons_gear-1.16.5-3.1.2-beta.jar
	Failure message: Dungeons Gear (dungeons_gear) encountered an error during the sided_setup event phase
		java.lang.NullPointerException: null
	Mod Version: 1.16.5-3.1.2-beta
	Mod Issue URL: http://my.issue.tracker/
	Exception message: java.lang.NullPointerException
Stacktrace:
	at com.infamous.dungeons_gear.items.VanillaItemModelProperties.<init>(VanillaItemModelProperties.java:17) ~[?:1.16.5-3.1.2-beta] {re:classloading}
	at com.infamous.dungeons_gear.DungeonsGear.doClientStuff(DungeonsGear.java:105) ~[?:1.16.5-3.1.2-beta] {re:classloading}
	at com.infamous.dungeons_gear.DungeonsGear$$Lambda$11413/1771151620.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2938/575197504.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3162/1477752059.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3801/893548422.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

**Comment by Patrigan** [comment]
We've recently confirmed server setup works. Please verify if this is fixed on your end too. if it is not, please reopen a ticket.
