### ISSUE TITLE
Unknown item 'minecraft:golden__sword'

### ISSUE THREAD

**Issue by pavog** [Thelnfamous1/Dungeons-Gear#158]
Hi, I get the following error on my Forge 1.16.5 server:

```
Parsing error loading recipe dungeons_gear:gold_sword_smithing
1100 | com.google.gson.JsonSyntaxException: Unknown item 'minecraft:golden__sword'
```

I use `dungeons_gear-1.16.5-3.0.21-hotfix.jar` on a Forge 1.16.5 (36.2.34) server.

Full error log:
```
[27Jun2022 04:48:42.388] [main/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Default, FarmersDelight-1.16.5-0.6.0.jar, create-stuff-additions1.16.5_v1.1.6.jar, mowziesmobs-1.5.25.jar, BiomesOPlenty-1.16.5-13.1.0.487-universal.jar, jei-1.16.5-7.7.1.152.jar, dungeons_mobs-1.16.5-2.0.3-beta.jar, abnormals_core-1.16.5-3.3.1.jar, flywheel-1.16-0.2.5.jar, alloyed-1.16.5-v0.3a.jar, steampowered-1.16.5-1.2.0-hf1.jar, curios-forge-1.16.5-4.0.8.2.jar, create-mc1.16.5_v0.3.2g.jar, createdeco-1.1.2-1.16.5.jar, citadel-1.8.1-1.16.5.jar, alexsmobs-1.12.1.jar, create-confectionery1.16.5_v1.0.2.jar, sophisticatedbackpacks-1.16.5-3.15.15.607.jar, cavebiomeapi-1.16.5-1.4.2.jar, forge-1.16.5-36.2.34-universal.jar, endergetic-1.16.5-3.0.2.jar, geckolib-forge-1.16.5-3.0.81.jar, dungeons_libraries-1.16.5-0.0.9-beta.jar, dungeons_gear-1.16.5-3.0.21-hotfix.jar
--
1098 | [27Jun2022 04:48:46.813] [Worker-Main-4/INFO] [com.minecraftabnormals.abnormals_core.core.AbnormalsCore/]: Loot Modification Manager has loaded 0 sets of modifiers
1099 | [27Jun2022 04:48:47.277] [Worker-Main-4/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe dungeons_gear:gold_sword_smithing
1100 | com.google.gson.JsonSyntaxException: Unknown item 'minecraft:golden__sword'
1101 | at net.minecraft.item.crafting.Ingredient.lambda$valueFromJson$11(Ingredient.java:216) ~[?:?]
1102 | at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_292]
1103 | at net.minecraft.item.crafting.Ingredient.func_199803_a(Ingredient.java:215) ~[?:?]
1104 | at net.minecraftforge.common.crafting.VanillaIngredientSerializer.parse(VanillaIngredientSerializer.java:41) ~[forge:?]
1105 | at net.minecraftforge.common.crafting.CraftingHelper.getIngredient(CraftingHelper.java:155) ~[forge:?]
1106 | at net.minecraft.item.crafting.Ingredient.func_199802_a(Ingredient.java:189) ~[?:?]
1107 | at net.minecraft.item.crafting.SmithingRecipe$Serializer.func_199425_a_(SmithingRecipe.java:70) ~[?:?]
1108 | at net.minecraft.item.crafting.SmithingRecipe$Serializer.func_199425_a_(SmithingRecipe.java:68) ~[?:?]
1109 | at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:141) ~[?:?]
1110 | at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:61) ~[?:?]
1111 | at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:38) ~[?:?]
1112 | at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?]
1113 | at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_292]
1114 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_292]
1115 | at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_292]
1116 | at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
1117 | at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?]
1118 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) ~[?:1.8.0_292]
1119 | at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) ~[?:1.8.0_292]
1120 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_292]
1121 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_292]
1122 | at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575) ~[?:1.8.0_292]
1123 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649) ~[?:1.8.0_292]
1124 | at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_292]
1125 | at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
1126 | at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?]
1127 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) ~[?:1.8.0_292]
1128 | at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) ~[?:1.8.0_292]
1129 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_292]
1130 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_292]
1131 | at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575) ~[?:1.8.0_292]
1132 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649) ~[?:1.8.0_292]
1133 | at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_292]
1134 | at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
1135 | at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?]
1136 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) ~[?:1.8.0_292]
1137 | at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) ~[?:1.8.0_292]
1138 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_292]
1139 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_292]
1140 | at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575) ~[?:1.8.0_292]
1141 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649) ~[?:1.8.0_292]
1142 | at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_292]
1143 | at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
1144 | at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?]
1145 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) ~[?:1.8.0_292]
1146 | at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) ~[?:1.8.0_292]
1147 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_292]
1148 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_292]
1149 | at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) ~[?:1.8.0_292]
1150 | at net.minecraft.resources.AsyncReloader$1.func_216873_a(SourceFile:53) ~[?:?]
1151 | at net.minecraft.resources.AsyncReloader$1.func_216872_a(SourceFile:50) ~[?:?]
1152 | at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) [?:1.8.0_292]
1153 | at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) [?:1.8.0_292]
1154 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_292]
1155 | at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) [?:1.8.0_292]
1156 | at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_292]
1157 | at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_292]
1158 | at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_292]
1159 | at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_292]
1160 | at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_292]
1161 | [27Jun2022 04:48:47.298] [Worker-Main-4/INFO] [net.minecraft.item.crafting.RecipeManager/]: Loaded 21 recipes
```

https://mclo.gs/3nJmnkv

**Comment by Patrigan** [comment]
This is fixed in the latest betas.
