### ISSUE TITLE
Love Medallion causes ticking entity

### ISSUE THREAD

**Issue by Arriochh** [Thelnfamous1/Dungeons-Gear#168]
I'm not sure what's happening to the server. Whenever I use the love medallion the entity ticks and crashes the server.

 ---- Minecraft Crash Report ----
// There are four lights!

Time: 10/20/22 8:58 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.infamous.dungeons_libraries.capabilities.minionmaster.Minion.setMaster(Minion.java:44) ~[dungeons_libraries:1.16.5-0.0.15-beta] {re:classloading}
	at com.infamous.dungeons_libraries.capabilities.minionmaster.MinionMasterHelper.removeMinion(MinionMasterHelper.java:116) ~[dungeons_libraries:1.16.5-0.0.15-beta] {re:mixin,re:classloading}
	at com.infamous.dungeons_libraries.capabilities.minionmaster.MinionEvents.onLivingEntityTick(MinionEvents.java:45) ~[dungeons_libraries:1.16.5-0.0.15-beta] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_377_MinionEvents_onLivingEntityTick_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:326) ~[forge:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2114) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:APP:enhancedcelestials.mixins.json:MixinLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dungeons_libraries.mixins.json:MobEntityInvoker,pl:mixin:APP:dungeons_libraries.mixins.json:MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:612) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:405) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.infamous.dungeons_libraries.capabilities.minionmaster.Minion.setMaster(Minion.java:44) ~[dungeons_libraries:1.16.5-0.0.15-beta] {re:classloading}
	at com.infamous.dungeons_libraries.capabilities.minionmaster.MinionMasterHelper.removeMinion(MinionMasterHelper.java:116) ~[dungeons_libraries:1.16.5-0.0.15-beta] {re:mixin,re:classloading}
	at com.infamous.dungeons_libraries.capabilities.minionmaster.MinionEvents.onLivingEntityTick(MinionEvents.java:45) ~[dungeons_libraries:1.16.5-0.0.15-beta] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_377_MinionEvents_onLivingEntityTick_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:326) ~[forge:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2114) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:APP:enhancedcelestials.mixins.json:MixinLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dungeons_libraries.mixins.json:MobEntityInvoker,pl:mixin:APP:dungeons_libraries.mixins.json:MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:612) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:A,pl:runtimedistcleaner:A}
-- Entity being ticked --
Details:
	Entity Type: minecraft:skeleton (net.minecraft.entity.monster.SkeletonEntity)
	Entity ID: 1447
	Entity Name: Skeleton
	Entity's Exact location: -31.30, 66.00, 40.63
	Entity's Block location: World: (-32,66,40), Chunk: (at 0,4,8 in -2,2; contains blocks -32,0,32 to -17,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:405) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:A,pl:runtimedistcleaner:A}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Arrioch'/1347, l='ServerLevel[world]', x=-34.38, y=66.00, z=43.71]]
	Chunk stats: ServerChunkCache: 2025
	Level dimension: minecraft:overworld
	Level spawn location: World: (-43,64,47), Chunk: (at 5,4,15 in -3,2; contains blocks -48,0,32 to -33,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2924 game time, 2924 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 166211 (now: false), thunder time: 61373 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 3.10.0-1160.36.2.el7.x86_64
	Java Version: 1.8.0_312, Red Hat, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Red Hat, Inc.
	Memory: 3134701480 bytes (2989 MB) / 4161798144 bytes (3969 MB) up to 4161798144 bytes (3969 MB)
	CPUs: 2
	JVM Flags: 2 total; -Xmx4096M -Xms2662M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge_1.16.5.jar object_holder_definalize PLUGINSERVICE 
		/forge_1.16.5.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge_1.16.5.jar capability_inject_definalize PLUGINSERVICE 
		/forge_1.16.5.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge_1.16.5.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.39-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		BroomsMod-1.16.5-1.1.0.jar                        |Brooms                        |broomsmod                     |1.16.5-1.1.0        |DONE      |Manifest: NOSIGNATURE
		CreativeCore_v2.2.1_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |DONE      |Manifest: NOSIGNATURE
		dungeons_mobs-1.16.5-2.0.3-beta.jar               |Dungeons Mobs                 |dungeons_mobs                 |1.16.5-2.0.3-beta   |DONE      |Manifest: NOSIGNATURE
		born_in_chaos_1.16_1.3.jar                        |Born in Chaos                 |born_in_chaos_v1              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		EyesInTheDarkness-1.16.5-1.0.6.jar                |Eyes in the Darkness          |eyesinthedarkness             |1.0.6               |DONE      |Manifest: NOSIGNATURE
		playerex-1.1.8-1.16.5.jar                         |Player Ex                     |playerex                      |1.1.8               |DONE      |Manifest: NOSIGNATURE
		SchoolsOfMagic1.16.5-2.1.04.jar                   |Schools of Magic: Second Semes|schoolsofmagic                |2.1.03              |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.8.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.8.2      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.3.jar                         |Patchouli                     |patchouli                     |1.16.4-53.3         |DONE      |Manifest: NOSIGNATURE
		Placebo-1.16.5-4.7.0.jar                          |Placebo                       |placebo                       |4.7.0               |DONE      |Manifest: NOSIGNATURE
		LibX-1.16.3-1.0.76.jar                            |LibX                          |libx                          |1.16.3-1.0.76       |DONE      |Manifest: NOSIGNATURE
		champions-forge-1.16.5-2.0.1.14.jar               |Champions                     |champions                     |1.16.5-2.0.1.14     |DONE      |Manifest: NOSIGNATURE
		relicex-1.0.0-1.16.4.jar                          |Relic Ex                      |relicex                       |1.0.0               |DONE      |Manifest: NOSIGNATURE
		MutantBeasts-1.16.4-1.1.3.jar                     |Mutant Beasts                 |mutantbeasts                  |1.16.4-1.1.3        |DONE      |Manifest: d9:be:bd:b6:9a:e4:14:aa:05:67:fb:84:06:77:a0:c5:10:ec:27:15:1b:d6:c0:88:49:9a:ef:26:77:61:0b:5e
		OnlyLooking-1.16.5-1.0.0.jar                      |OnlyLooking                   |onlylooking                   |1.16.5-1.0.0        |DONE      |Manifest: NOSIGNATURE
		FastFurnace-1.16.5-4.5.0.jar                      |FastFurnace                   |fastfurnace                   |4.5.0               |DONE      |Manifest: NOSIGNATURE
		architectury-1.32.66.jar                          |Architectury                  |architectury                  |1.32.66             |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-1605.3.4-build.90.jar           |FTB Library                   |ftblibrary                    |1605.3.4-build.90   |DONE      |Manifest: NOSIGNATURE
		enhancedcelestials-2.0.9-1.16.5.jar               |Enhanced Celestials           |enhancedcelestials            |2.0.9-1.16.5        |DONE      |Manifest: NOSIGNATURE
		ftb-teams-forge-1605.2.3-build.40.jar             |FTB Teams                     |ftbteams                      |1605.2.3-build.40   |DONE      |Manifest: NOSIGNATURE
		ftb-chunks-forge-1605.3.2-build.115.jar           |FTB Chunks                    |ftbchunks                     |1605.3.2-build.115  |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		AutoLeveling-1.16.5-1.10a.jar                     |Auto Leveling                 |autoleveling                  |1.10a               |DONE      |Manifest: NOSIGNATURE
		PlayerRevive_v2.0.0-pre04_mc1.16.5.jar            |PlayerRevive                  |playerrevive                  |2.0.0               |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.96.jar                  |GeckoLib                      |geckolib3                     |3.0.96              |DONE      |Manifest: NOSIGNATURE
		effortlessbuilding-1.16.3-2.29.jar                |Effortless Building           |effortlessbuilding            |1.16.3-2.29         |DONE      |Manifest: NOSIGNATURE
		dungeons_libraries-1.16.5-0.0.15-beta.jar         |Dungeons Libraries            |dungeons_libraries            |1.16.5-0.0.15-beta  |DONE      |Manifest: NOSIGNATURE
		dungeons_gear-1.16.5-3.1.15-beta.jar              |Dungeons Gear                 |dungeons_gear                 |1.16.5-3.1.15-beta  |DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.16.5-2.1.49-beta.jar              |When Dungeons Arise           |dungeons_arise                |2.1.49              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 141faf4c-2d66-4ae9-a685-658f2a111711
	Player Count: 1 / 100; [ServerPlayerEntity['Arrioch'/1347, l='ServerLevel[world]', x=-34.38, y=66.00, z=43.71]]
	Data Packs: vanilla, mod:broomsmod, mod:creativecore, mod:dungeons_mobs (incompatible), mod:born_in_chaos_v1, mod:eyesinthedarkness (incompatible), mod:playerex, mod:schoolsofmagic, mod:curios, mod:patchouli (incompatible), mod:placebo (incompatible), mod:libx, mod:champions (incompatible), mod:relicex, mod:mutantbeasts (incompatible), mod:onlylooking, mod:fastfurnace (incompatible), mod:architectury, mod:ftblibrary, mod:enhancedcelestials, mod:ftbteams, mod:ftbchunks, mod:forge, mod:autoleveling, mod:playerrevive, mod:geckolib3 (incompatible), mod:effortlessbuilding (incompatible), mod:dungeons_libraries (incompatible), mod:dungeons_gear, mod:dungeons_arise
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Patrigan** [comment]
Fixed in the upcoming beta 3.1.17-beta
