### ISSUE TITLE
I think there is an issue bartering with piglins 

### ISSUE THREAD

**Issue by Seanniex** [Thelnfamous1/Dungeons-Gear#2]
Here is the crash report 

Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.util.math.BlockPos.<init>(SourceFile:56) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at com.infamous.dungeons_gear.loot.GlobalLootModifier$CommonLootAdditions.doApply(GlobalLootModifier.java:66) ~[?:2.0.1] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:53) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1199) ~[?:?] {re:classloading}
	at net.minecraft.loot.LootTable.func_216113_a(LootTable.java:86) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.entity.monster.piglin.PiglinTasks.func_234524_k_(PiglinTasks.java:304) ~[?:?] {re:classloading}
	at net.minecraft.entity.monster.piglin.PiglinTasks.func_234477_a_(PiglinTasks.java:237) ~[?:?] {re:classloading}
	at net.minecraft.entity.monster.piglin.StartAdmiringItemTask.func_212831_a_(SourceFile:24) ~[?:?] {re:classloading}
	at net.minecraft.entity.monster.piglin.StartAdmiringItemTask.func_212831_a_(SourceFile:10) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.task.Task.func_220378_b(SourceFile:49) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.Brain.func_218218_d(SourceFile:506) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.Brain.func_218210_a(SourceFile:465) ~[?:?] {re:classloading}
	at net.minecraft.entity.monster.piglin.PiglinEntity.func_70619_bc(PiglinEntity.java:226) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:982) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:682) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:43) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:430) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:606) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld$$Lambda$9519/537837893.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:399) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:120) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$8846/499304279.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.util.math.BlockPos.<init>(SourceFile:56) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at com.infamous.dungeons_gear.loot.GlobalLootModifier$CommonLootAdditions.doApply(GlobalLootModifier.java:66) ~[?:2.0.1] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:53) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1199) ~[?:?] {re:classloading}
	at net.minecraft.loot.LootTable.func_216113_a(LootTable.java:86) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.entity.monster.piglin.PiglinTasks.func_234524_k_(PiglinTasks.java:304) ~[?:?] {re:classloading}
	at net.minecraft.entity.monster.piglin.PiglinTasks.func_234477_a_(PiglinTasks.java:237) ~[?:?] {re:classloading}
	at net.minecraft.entity.monster.piglin.StartAdmiringItemTask.func_212831_a_(SourceFile:24) ~[?:?] {re:classloading}
	at net.minecraft.entity.monster.piglin.StartAdmiringItemTask.func_212831_a_(SourceFile:10) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.task.Task.func_220378_b(SourceFile:49) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.Brain.func_218218_d(SourceFile:506) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.Brain.func_218210_a(SourceFile:465) ~[?:?] {re:classloading}
	at net.minecraft.entity.monster.piglin.PiglinEntity.func_70619_bc(PiglinEntity.java:226) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:982) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:682) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:43) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:430) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:606) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld$$Lambda$9519/537837893.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: minecraft:piglin (net.minecraft.entity.monster.piglin.PiglinEntity)
	Entity ID: 122833
	Entity Name: Piglin
	Entity's Exact location: -5.53, 34.00, 30.62
	Entity's Block location: World: (-6,34,30), Chunk: (at 10,2,14 in -1,1; contains blocks -16,0,16 to -1,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:399) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}

Mod List: 
		mining-helmet-1.16.3-1.0.9.jar Mining Helmet {mining_helmet@1.0.9 DONE}
		spiders-2.0-1.16.3-1.0.1.jar Spiders 2.0 {spiderstpo@1.0.1 DONE}
		beta_days-1.16.3-1.1.4.jar Beta Days {beta_days@1.1.4 DONE}
		curiousshulkerboxes-forge-1.16.3-4.0.0.1.jar Curious Shulker Boxes {curiousshulkerboxes@1.16.3-4.0.0.1 DONE}
		jei-1.16.3-7.3.2.36.jar Just Enough Items {jei@7.3.2.29 DONE}
		OptiForge-MC1.16.3-0.3.3.jar OptiForge {optiforge@0.3.3 DONE}
		mooshroomtweaks_1.16.3_1.2.jar Mooshroom Tweaks {mooshroomtweaks@1.2 DONE}
		the-conjurer-1.16.3-1.0.11.jar The Conjurer {conjurer_illager@1.0.11 DONE}
		callablehorses-1.16.3-1.2.0.2.jar Callable Horses {callablehorses@1.2.0.2 DONE}
		Tiny-Coal-1.16.3-1.0.0.jar Tiny Coal {tinycoal@1.0.0 DONE}
		goblintraders-1.2.2-1.16.3.jar Goblin Traders {goblintraders@1.2.2 DONE}
		seals-1.16.3-2.0.0.jar Seals {seals@2.0.0 DONE}
		gildedarmor-1.16.3-1.0.2.jar Gilded Armor {gildedarmor@1.0.2 DONE}
		BetterCaves-1.16.2-1.0.3.jar YUNG's Better Caves {bettercaves@1.16.2-1.0.3 DONE}
		Waystones_1.16.3-7.3.0.jar Waystones {waystones@7.3.0 DONE}
		NeverNeededOrWanted-1.16.3-1.0.4.jar Never Needed Or Wanted {nnow@1.16.3-1.0.4 DONE}
		Placebo-1.16.3-4.3.1.jar Placebo {placebo@4.3.1 DONE}
		comforts-forge-1.16.2-4.0.0.0.jar Comforts {comforts@1.16.2-4.0.0.0 DONE}
		citadel-1.4.0.jar Citadel {citadel@1.4.0 DONE}
		premium-wood-1.16.3-1.3.0.jar Premium Wood {premium_wood@1.3.0 DONE}
		jumbofurnace-1.16.3-2.0.0.1.jar Jumbo Furnace {jumbofurnace@1.16.3-2.0.0.1 DONE}
		champions-forge-1.16.3-2.0.0.1.jar Champions {champions@1.16.3-2.0.0.1 DONE}
		DungeonCrawl-1.16.3-2.1.1.jar Dungeon Crawl {dungeoncrawl@2.1.1 DONE}
		curioofundying-forge-1.16.3-5.0.0.1.jar Curio of Undying {curioofundying@1.16.3-5.0.0.1 DONE}
		MutantBeasts-1.16.3-1.1.2.jar Mutant Beasts {mutantbeasts@1.16.3-1.1.2 DONE}
		Reliquary-1.16.3-1.3.4.1015.jar Reliquary {xreliquary@1.16.3-1.3.4.1015 DONE}
		guardvillagers-1.16.3-1.1.5.jar Guard Villagers {guardvillagers@1.1.5 DONE}
		Actually.Useful.Smithing.Table-1.0.2.mc.1.16.3.jar Actually Useful Smithing Table {actuallyusefulsmithingtable@1.0.2 mc 1.16.3 DONE}
		simpleplanes-1.16.3-3.1.0.0.jar Simple Planes {simpleplanes@1.16.3-3.1.0.0 DONE}
		Apotheosis-1.16.3-4.3.1.jar Apotheosis {apotheosis@4.3.1 DONE}
		pollinatlor-1.16.x-1.0.1.jar Pollinator {pollinator@1.16.x-1.0.1 DONE}
		iceandfire-2.1.0-1.16.3.jar Ice and Fire {iceandfire@2.0.3-1.16.3 DONE}
		sculktastic.jar Sculktastic {sculktastic@1.16.3-2.0 DONE}
		pathundergates-1.16.3-1.0.0-release.jar Path Under Gates {pathundergates@1.16.3-1.0.0-release DONE}
		fixedanvilrepaircost_1.16.3_1.1.jar Fixed Anvil Repair Cost {fixedanvilrepaircost@1.1 DONE}
		dads_sewing-6.0.jar Dad's Sewing {dads_sewing@6.0 DONE}
		SBM-Merpig-1.16.3-0.0.1.jar [SBM] Merpig {merpig@0.0.1 DONE}
		JustEnoughResources-1.16.3-0.12.0.100.jar Just Enough Resources {jeresources@0.12.0.100 DONE}
		horsestandstill-1.16.3-1.0.1.jar Stupid Horse Stand Still {horsestandstill@1.16.3-1.0.1 DONE}
		forge-1.16.3-34.1.19-universal.jar Forge {forge@34.1.19 DONE}
		scuba-gear-1.16.3-1.0.1.jar Scuba Gear {scuba_gear@1.0.1 DONE}
		EnderTendril-1.16.3-1.1.1+4.jar Ender Tendril {endertendril@1.1.1+4 DONE}
		structure-gel-api-1.16.3-1.4.2.jar Structure Gel API {structure_gel@1.4.2 DONE}
		smarthud-1.1-1.16.3.jar Smarter HUD {smarthud@1.1-1.16.3 DONE}
		forge-1.16.3-34.1.19-client.jar Minecraft {minecraft@1.16.3 DONE}
		repurposed_structures-1.16.3-2.2.6.jar Repurposed Structures {repurposed_structures@1.16.3-2.2.6 DONE}
		netherportalspread_1.16.3-4.3.jar Nether Portal Spread {netherportalspread@4.3 DONE}
		EmmyStuff-1.16.3-1.1.0.1.jar Emmy Stuff {emmystuff@1.16.3-1.1.0.1 DONE}
		dungeons-plus-1.16.3-1.0.3.jar Dungeons Plus {dungeons_plus@1.0.3 DONE}
		forbidden_arcanus-1.16.3-1.0.1.jar Forbidden & Arcanus {forbidden_arcanus@1.16.3-1.0.1 DONE}
		simplefarming-1.16.3-1.3.3.jar Simple Farming {simplefarming@1.16.3-1.3.3 DONE}
		villagespawnpoint_1.16.3_1.3.jar Village Spawn Point {villagespawnpoint@1.3 DONE}
		Trapcraft-1.16.3-3.2.1.jar Trapcraft {trapcraft@3.2.1 DONE}
		curios-forge-1.16.3-4.0.2.0.jar Curios API {curios@1.16.3-4.0.2.0 DONE}
		Patchouli-1.16.2-44.jar Patchouli {patchouli@1.16.2-44 DONE}
		leap-1.16.3-1.0.1.jar Leap {leap@1.0.1 DONE}
		rndbmflowers_1.16.3_1.2.jar Random Bone Meal Flowers {rndbmflowers@1.2 DONE}
		rats-7.0.0-1.16.3.jar Rats {rats@7.0.0 DONE}
		collective-1.16.3-1.51.jar Collective {collective@1.51 DONE}
		nightterror-1.0.jar Night Terror {nightterror@1.0 DONE}
		polymorph-forge-1.16.3-0.15.jar Polymorph {polymorph@1.16.3-0.15 DONE}
		earthmobsmod-1.16.3-0.1.2-Beta.jar Earth Mobs Mod {earthmobsmod@1.16.3-0.1.2-Beta DONE}
		backpacked-1.5.2-1.16.3.jar Backpacked {backpacked@1.5.2 DONE}
		xercapaint-1.16.3-1.0.jar Joy of Painting {xercapaint@1.16.3-1.0 DONE}
		Regrowth-1.16.2-1.16.3-1.21.0.14.jar Regrowth Mod {regrowth@1.21.0.14 DONE}
		EnigmaticLegacy-2.6.1.jar Enigmatic Legacy {enigmaticlegacy@2.6.1 DONE}
		buildersaddition-1.16.3-20200930a.jar Builders Crafts & Addition {buildersaddition@1.16.3-20200930a DONE}
		constructionwand-1.16.2-1.5.jar Construction Wand {constructionwand@1.16.2-1.5 DONE}
		hunterillager-1.16.3-1.0.2.jar HunterIllager {hunterillager@1.0.0 DONE}
		productivebees-1.16.2-0.3.5.2.jar Productive Bees {productivebees@1.16.2-0.3.5.2 DONE}
		Aquaculture-1.16.3-2.1.1.jar Aquaculture 2 {aquaculture@1.16.3-2.1.1 DONE}
		snowbfrmobs_1.16.3_1.1.jar Snowballs Freeze Mobs {snowbfrmobs@1.1 DONE}
		enchantwithmob-1.16.3-1.6.1.jar Enchant With Mob {enchantwithmob@1.16.3-1.6.1 DONE}
		BetterBurning-1.16.3-4.0.2.jar BetterBurning {betterburning@4.0.2 DONE}
		strayspawn_1.16.3_1.1.jar Stray Spawn {strayspawn@1.1 DONE}
		CosmeticArmorReworked-1.16.3-v1.jar CosmeticArmorReworked {cosmeticarmorreworked@1.16.3-v1 DONE}
		entityarmormodels-1.16.3-1.1.1.0.jar �1Entity �cArmor �fModels {entityarmormodels@1.16.3-1.1.1.0 DONE}
		BetterMineshaftsForge-1.16.2-1.0.jar YUNG's Better Mineshafts {bettermineshafts@1.16.2-1.0 DONE}
		dungeons_gear-1.16.2+1.16.3-2.0.1.jar Dungeons Gear {dungeons_gear@2.0.1 DONE}
		farlanders-1.16.3-1.3.4.jar The Farlanders {farlanders@1.3.4 DONE}

**Comment by Thelnfamous1** [comment]
Fixed in latest
