### ISSUE TITLE
[1.16.5] Crash while picking dual crossbow with "parry this" mod installed.

### ISSUE THREAD

**Issue by DmitryKarnaukhov** [Thelnfamous1/Dungeons-Gear#213]
Server stoped while picking dual crossbow with parry this mod installed.
My mods when crash occurs:
Forge
dungeons_gear-1.16.5-3.2.6
dungeons_libraries-1.16.5-1.0.6
parrying-unofficial-2.2.2a
[OptiFine-OptiFine-1.16.5_HD_U_G8_pre2.jar

Description: Ticking player

java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_51] {}
	at net.minecraft.entity.player.PlayerEntity.handler$bbb000$InjectIntoGetCurrentItemAttackStrengthDelay(PlayerEntity.java:8673) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:mixin,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:classloading,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,pl:mixin:APP:dynamiclightsreforged.mixins.json:PlayerEntityMixin,pl:mixin:APP:betterendforge.mixins.json:PlayerEntityMixin,pl:mixin:APP:dungeons_gear.mixins.json:PlayerEntityMixin,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:shouldersurfing.mixins.json:MixinPlayerEntity,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:environmental.mixins.json:PlayerEntityMixin,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:allurement.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.PlayerEntityAccessor,pl:mixin:APP:expandability.mixins.json:swimming.PlayerMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:APP:mixins.parrying.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_184818_cX(PlayerEntity.java) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:mixin,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:classloading,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,pl:mixin:APP:dynamiclightsreforged.mixins.json:PlayerEntityMixin,pl:mixin:APP:betterendforge.mixins.json:PlayerEntityMixin,pl:mixin:APP:dungeons_gear.mixins.json:PlayerEntityMixin,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:shouldersurfing.mixins.json:MixinPlayerEntity,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:environmental.mixins.json:PlayerEntityMixin,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:allurement.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.PlayerEntityAccessor,pl:mixin:APP:expandability.mixins.json:swimming.PlayerMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:APP:mixins.parrying.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_184825_o(PlayerEntity.java:1911) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:mixin,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:classloading,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,pl:mixin:APP:dynamiclightsreforged.mixins.json:PlayerEntityMixin,pl:mixin:APP:betterendforge.mixins.json:PlayerEntityMixin,pl:mixin:APP:dungeons_gear.mixins.json:PlayerEntityMixin,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:shouldersurfing.mixins.json:MixinPlayerEntity,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:environmental.mixins.json:PlayerEntityMixin,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:allurement.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.PlayerEntityAccessor,pl:mixin:APP:expandability.mixins.json:swimming.PlayerMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:APP:mixins.parrying.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.handler$znc000$addCombo(PlayerEntity.java:3205) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:mixin,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:classloading,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,pl:mixin:APP:dynamiclightsreforged.mixins.json:PlayerEntityMixin,pl:mixin:APP:betterendforge.mixins.json:PlayerEntityMixin,pl:mixin:APP:dungeons_gear.mixins.json:PlayerEntityMixin,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:shouldersurfing.mixins.json:MixinPlayerEntity,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:environmental.mixins.json:PlayerEntityMixin,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:allurement.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.PlayerEntityAccessor,pl:mixin:APP:expandability.mixins.json:swimming.PlayerMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:APP:mixins.parrying.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_184821_cY(PlayerEntity.java) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:mixin,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:classloading,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,pl:mixin:APP:dynamiclightsreforged.mixins.json:PlayerEntityMixin,pl:mixin:APP:betterendforge.mixins.json:PlayerEntityMixin,pl:mixin:APP:dungeons_gear.mixins.json:PlayerEntityMixin,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:shouldersurfing.mixins.json:MixinPlayerEntity,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:environmental.mixins.json:PlayerEntityMixin,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:allurement.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.PlayerEntityAccessor,pl:mixin:APP:expandability.mixins.json:swimming.PlayerMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:APP:mixins.parrying.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:257) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:mixin,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:classloading,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,pl:mixin:APP:dynamiclightsreforged.mixins.json:PlayerEntityMixin,pl:mixin:APP:betterendforge.mixins.json:PlayerEntityMixin,pl:mixin:APP:dungeons_gear.mixins.json:PlayerEntityMixin,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:shouldersurfing.mixins.json:MixinPlayerEntity,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:environmental.mixins.json:PlayerEntityMixin,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:allurement.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.PlayerEntityAccessor,pl:mixin:APP:expandability.mixins.json:swimming.PlayerMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:APP:mixins.parrying.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:endergetic.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:ServerPlayNetHandlerPlayerSpeedLimitsMixin,pl:mixin:APP:randompatches.mixins.json:timeouts.ServerPlayNetHandlerKeepAliveMixin,pl:mixin:APP:betterendforge.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ServerPlayNetHandlerAccess,pl:mixin:APP:endergetic.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:APP:tombstone.mixins.json:ServerPacketMixin,pl:mixin:A}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:kryptonreforged.mixins.json:network.shared.flushconsolidation.ClientConnectionMixin,pl:mixin:APP:kryptonreforged.mixins.json:network.shared.pipeline.compression.ClientConnectionMixin,pl:mixin:APP:kryptonreforged.mixins.json:network.shared.pipeline.encryption.ClientConnectionMixin,pl:mixin:A}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:APP:mixins.shrines.json:MixinMinecraftServer,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:APP:mixins.shrines.json:MixinMinecraftServer,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:APP:mixins.shrines.json:MixinMinecraftServer,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:APP:mixins.shrines.json:MixinMinecraftServer,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$33199/2008999861.run(Unknown Source) ~[?:?] {}
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_51] {}

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_51] {}
	at net.minecraft.entity.player.PlayerEntity.handler$bbb000$InjectIntoGetCurrentItemAttackStrengthDelay(PlayerEntity.java:8673) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:mixin,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:classloading,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,pl:mixin:APP:dynamiclightsreforged.mixins.json:PlayerEntityMixin,pl:mixin:APP:betterendforge.mixins.json:PlayerEntityMixin,pl:mixin:APP:dungeons_gear.mixins.json:PlayerEntityMixin,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:shouldersurfing.mixins.json:MixinPlayerEntity,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:environmental.mixins.json:PlayerEntityMixin,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:allurement.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.PlayerEntityAccessor,pl:mixin:APP:expandability.mixins.json:swimming.PlayerMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:APP:mixins.parrying.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_184818_cX(PlayerEntity.java) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:mixin,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:classloading,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,pl:mixin:APP:dynamiclightsreforged.mixins.json:PlayerEntityMixin,pl:mixin:APP:betterendforge.mixins.json:PlayerEntityMixin,pl:mixin:APP:dungeons_gear.mixins.json:PlayerEntityMixin,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:shouldersurfing.mixins.json:MixinPlayerEntity,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:environmental.mixins.json:PlayerEntityMixin,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:allurement.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.PlayerEntityAccessor,pl:mixin:APP:expandability.mixins.json:swimming.PlayerMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:APP:mixins.parrying.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_184825_o(PlayerEntity.java:1911) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:mixin,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:classloading,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,pl:mixin:APP:dynamiclightsreforged.mixins.json:PlayerEntityMixin,pl:mixin:APP:betterendforge.mixins.json:PlayerEntityMixin,pl:mixin:APP:dungeons_gear.mixins.json:PlayerEntityMixin,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:shouldersurfing.mixins.json:MixinPlayerEntity,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:environmental.mixins.json:PlayerEntityMixin,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:allurement.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.PlayerEntityAccessor,pl:mixin:APP:expandability.mixins.json:swimming.PlayerMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:APP:mixins.parrying.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.handler$znc000$addCombo(PlayerEntity.java:3205) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:mixin,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:classloading,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,pl:mixin:APP:dynamiclightsreforged.mixins.json:PlayerEntityMixin,pl:mixin:APP:betterendforge.mixins.json:PlayerEntityMixin,pl:mixin:APP:dungeons_gear.mixins.json:PlayerEntityMixin,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:shouldersurfing.mixins.json:MixinPlayerEntity,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:environmental.mixins.json:PlayerEntityMixin,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:allurement.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.PlayerEntityAccessor,pl:mixin:APP:expandability.mixins.json:swimming.PlayerMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:APP:mixins.parrying.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_184821_cY(PlayerEntity.java) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:mixin,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:classloading,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,pl:mixin:APP:dynamiclightsreforged.mixins.json:PlayerEntityMixin,pl:mixin:APP:betterendforge.mixins.json:PlayerEntityMixin,pl:mixin:APP:dungeons_gear.mixins.json:PlayerEntityMixin,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:shouldersurfing.mixins.json:MixinPlayerEntity,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:environmental.mixins.json:PlayerEntityMixin,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:allurement.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.PlayerEntityAccessor,pl:mixin:APP:expandability.mixins.json:swimming.PlayerMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:APP:mixins.parrying.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:257) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:mixin,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:classloading,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,pl:mixin:APP:dynamiclightsreforged.mixins.json:PlayerEntityMixin,pl:mixin:APP:betterendforge.mixins.json:PlayerEntityMixin,pl:mixin:APP:dungeons_gear.mixins.json:PlayerEntityMixin,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:shouldersurfing.mixins.json:MixinPlayerEntity,pl:mixin:APP:blue_skies.mixins.json:PlayerEntityMixin,pl:mixin:APP:environmental.mixins.json:PlayerEntityMixin,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:allurement.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.PlayerEntityAccessor,pl:mixin:APP:expandability.mixins.json:swimming.PlayerMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:APP:mixins.parrying.json:PlayerEntityMixin,pl:mixin:A}

**Comment by Thelnfamous1** [comment]
Looks like they are not checking to make sure the held weapons have attack speed attributes when checking for dual wield.
https://github.com/theishiopian/Parrying/blob/1.18_release/src/main/java/com/theishiopian/parrying/Mixin/PlayerMixin.java

**Comment by Thelnfamous1** [comment]
@DmitryKarnaukhov For now, add the dual crossbows to Parry This's Two-Handed weapons tag. I will speak to theishiopian about fixing this issue.

**Comment by DmitryKarnaukhov** [comment]
Thank you!

**Comment by Thelnfamous1** [comment]
Also, this crash will happen if you dual wield any two items that have attack damage modifiers but either one does not have attack speed modifiers. Be mindful of this and add items to the tag as necessary (I would add all of our ranged weapons, as we seem to be adding attack damage modifiers on them).

**Comment by DmitryKarnaukhov** [comment]
If it's not difficult for you, please tell me how to add a tag to an item.
I want to note that I did not encounter such problems with the previous version of your mod (dungeons_gear-1.16.5-3.1.2-beta).
Parrying(parry this) was the same version.

**Comment by Thelnfamous1** [comment]
https://minecraft.fandom.com/wiki/Data_pack

For "namespace" you would put "parrying" and for the JSON file under the item subfolder of tags you would put "two_handed_weapons" as its name. You'll want to mimic [this ](https://github.com/theishiopian/Parrying/blob/master/src/main/resources/data/parrying/tags/items/two_handed_weapons.json) format for your own file, putting as many of our mod's ranged weapons as you can, in the format of "dungeons_gear:weapon_name_in_lowercase_separated_by_underscore".
