### ISSUE TITLE
Crash on Forge 35.1.13 with DG 3.0.4

### ISSUE THREAD

**Issue by UnseenAcademical** [Thelnfamous1/Dungeons-Gear#22]
`[18:46:06] [pool-3-thread-1/FATAL]: Mixin apply failed dungeons_gear.mixins.json:HurtByTargetGoalMixin -> net.minecraft.entity.ai.goal.HurtByTargetGoal: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException PROTECTED @Overwrite method func_190105_f in dungeons_gear.mixins.json:HurtByTargetGoalMixin cannot reduce visibiliy of PUBLIC target method
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PROTECTED @Overwrite method func_190105_f in dungeons_gear.mixins.json:HurtByTargetGoalMixin cannot reduce visibiliy of PUBLIC target method
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.conformVisibility(MixinPreProcessorStandard.java:472) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:445) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachOverwriteMethod(MixinPreProcessorStandard.java:406) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:336) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:289) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:267) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1271) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) [modlauncher-8.0.6.jar:8.0.6+85+master.325de55]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:119) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) [modlauncher-8.0.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_51]
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962) [?:1.8.0_51]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:987) [?:1.8.0_51]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1390) [?:1.8.0_51]
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1746) [?:1.8.0_51]
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) [?:1.8.0_51]
	at net.minecraft.entity.EntityType.<clinit>(EntityType.java:152) [?:?]
	at net.minecraft.world.gen.feature.DungeonsFeature.<clinit>(DungeonsFeature.java:24) [?:?]
	at net.minecraft.world.gen.feature.Feature.<clinit>(Feature.java:37) [?:?]
	at net.minecraft.world.gen.feature.Features.<clinit>(SourceFile:92) [?:?]
	at net.minecraft.util.registry.WorldGenRegistries.lambda$static$2(WorldGenRegistries.java:39) [?:?]
	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$638/804314228.get(Unknown Source) [?:?]
	at net.minecraft.util.registry.WorldGenRegistries.lambda$static$6(WorldGenRegistries.java:89) [?:?]
	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$644/1161271936.accept(Unknown Source) [?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676) [?:1.8.0_51]
	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88) [?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464) [?:?]
	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38) [?:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123) [?:?]
	at net.minecraft.client.main.Main$$Lambda$582/1183266411.run(Unknown Source) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]`

**Comment by Thelnfamous1** [comment]
Let me guess. You are playing this alongside Resourceful Bees.

**Comment by UnseenAcademical** [comment]
Yes. Expected behavior? I hadn't seen anything about incompatibility with RB.

**Comment by Thelnfamous1** [comment]
I should pin it, the dev said they'd fix it but I guess they haven't gotten around to it.
