### ISSUE TITLE
Crash with dungeons gear and latest quark relating to stoneling

### ISSUE THREAD

**Issue by Snorps** [Thelnfamous1/Dungeons-Gear#3]
`---- Minecraft Crash Report ----
// Don't do that.

Time: 21/10/20 21:16
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.util.math.BlockPos.<init>(SourceFile:56) ~[?:?] {re:mixin,re:classloading}
	at com.infamous.dungeons_gear.loot.GlobalLootModifier$CommonLootAdditions.doApply(GlobalLootModifier.java:66) ~[?:2.0.1] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:53) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1210) ~[?:?] {re:classloading}
	at net.minecraft.loot.LootTable.func_216113_a(LootTable.java:86) ~[?:?] {re:mixin,re:classloading}
	at vazkii.quark.mobs.entity.StonelingEntity.func_213386_a(StonelingEntity.java:274) ~[?:r2.4-269] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:175) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:124) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:110) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(SourceFile:388) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_144] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:368) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:337) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:328) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:80) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.util.math.BlockPos.<init>(SourceFile:56) ~[?:?] {re:mixin,re:classloading}
	at com.infamous.dungeons_gear.loot.GlobalLootModifier$CommonLootAdditions.doApply(GlobalLootModifier.java:66) ~[?:2.0.1] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:53) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1210) ~[?:?] {re:classloading}
	at net.minecraft.loot.LootTable.func_216113_a(LootTable.java:86) ~[?:?] {re:mixin,re:classloading}
	at vazkii.quark.mobs.entity.StonelingEntity.func_213386_a(StonelingEntity.java:274) ~[?:r2.4-269] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:175) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:124) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:110) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(SourceFile:388) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_144] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:368) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:337) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:328) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Snorpy'/197, l='ServerLevel[New World]', x=6.50, y=100.00, z=194.50]]
	Chunk stats: ServerChunkCache: 2116
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,100,192), Chunk: (at 0,6,0 in 0,12; contains blocks 0,0,192 to 15,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 65 game time, 65 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 51457 (now: false), thunder time: 174778 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:80) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144] {}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2957333072 bytes (2820 MB) / 4105175040 bytes (3915 MB) up to 4105175040 bytes (3915 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx4096m
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.25-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.25-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.25-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.25-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.25-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.25
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.25-client.jar Minecraft {minecraft@1.16.3 DONE}
		forge-1.16.3-34.1.25-universal.jar Forge {forge@34.1.25 DONE}
		dungeons_gear-1.16.2+1.16.3-2.0.1.jar Dungeons Gear {dungeons_gear@2.0.1 DONE}
		AutoRegLib-1.6-46.jar AutoRegLib {autoreglib@1.6-46 DONE}
		Quark-r2.4-269.jar Quark {quark@r2.4-269 DONE}
	Crash Report UUID: 9fff9fd5-0a38-4fc3-8c93-8c90eeb0636d
	Player Count: 1 / 8; [ServerPlayerEntity['Snorpy'/197, l='ServerLevel[New World]', x=6.50, y=100.00, z=194.50]]
	Data Packs: vanilla, mod:forge, mod:dungeons_gear, mod:autoreglib (incompatible), mod:quark (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'`

Happens instantly on new world generation.

**Comment by Snorps** [comment]
can be avoided by disabling stonelings in quark's config

**Comment by Thelnfamous1** [comment]
Same as #2 , easy to fix although seems dumb. A BlockPos is null when it should not be.

**Comment by Snorps** [comment]
ahhh cool!

**Comment by Thelnfamous1** [comment]
Fixed in latest.
