### ISSUE TITLE
Crossbows Crashing the game when fired 

### ISSUE THREAD

**Issue by simplemath64** [Thelnfamous1/Dungeons-Gear#5]
I don't know what's causing this, every time i fire one of the crossbows it just freezes the game.  Doesn't even crash the client just freezes and stalls. I have optifine installed and some other mods but I didn't think any would cause this.

Here's the crash log after I manually close the game, 

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 10/31/20 11:58 AM
Description: Exception in server tick loop

java.lang.IllegalAccessError: tried to access method net.minecraft.item.CrossbowItem.func_220018_j(Lnet/minecraft/item/ItemStack;)Ljava/util/List; from class com.infamous.dungeons_gear.ranged.crossbows.BurstCrossbowItem
	at com.infamous.dungeons_gear.ranged.crossbows.BurstCrossbowItem.fireCrossbowProjectiles(BurstCrossbowItem.java:46) ~[?:2.0.11] {re:classloading}
	at com.infamous.dungeons_gear.ranged.crossbows.AbstractDungeonsCrossbowItem.func_77659_a(AbstractDungeonsCrossbowItem.java:61) ~[?:2.0.11] {re:classloading}
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:214) ~[?:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A}
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:287) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147346_a(ServerPlayNetHandler.java:913) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:backpacked:creative_inventory_action_fix}
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:31) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:9) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.network.PacketThreadUtil$$Lambda$8732/919089472.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:172) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:729) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:156) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:134) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:712) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:706) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:150) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:692) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$7838/1259100316.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 719532128 bytes (686 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.1.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.1.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.3_HD_U_G3.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.0
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.0-client.jar Minecraft {minecraft@1.16.3 DONE}
		repurposed_structures-1.16.3-2.2.11.jar Repurposed Structures {repurposed_structures@1.16.3-2.2.11 DONE}
		thirdpersonelytra-1.16.2-1.2.jar Third Person Elytra {thirdpersonelytra@version DONE}
		ElenaiDodge-1.16.2-1.7.2.jar Elenai Dodge {elenaidodge@1.16.2-1.7.2 DONE}
		spiders-2.0-1.16.3-1.0.3.jar Spiders 2.0 {spiderstpo@1.0.3 DONE}
		LetSleepingDogsLie-1.16.3-1.1.1.jar Let Sleeping Dogs Lie {dogslie@1.1.1 DONE}
		goblintraders-1.2.2-1.16.3.jar Goblin Traders {goblintraders@1.2.2 DONE}
		torohealth-1.16.3-forge-2.jar ToroHealth {torohealth@NONE DONE}
		strawgolem-1.16-1.9.jar Straw Golem {strawgolem@1.16-1.9 DONE}
		curios-forge-1.16.3-4.0.2.0.jar Curios API {curios@1.16.3-4.0.2.0 DONE}
		Botania-1.16.3-409.jar Botania {botania@1.16.3-409 DONE}
		Patchouli-1.16.2-47.jar Patchouli {patchouli@1.16.2-47 DONE}
		BetterCaves-1.16.2-1.0.4.jar YUNG's Better Caves {bettercaves@1.16.2-1.0.4 DONE}
		Xaeros_Minimap_20.26.0_Forge_1.16.3.jar Xaero's Minimap {xaerominimap@20.26.0 DONE}
		Waystones_1.16.3-7.3.0.jar Waystones {waystones@7.3.0 DONE}
		gravestone-1.16.3-1.0.2.jar Gravestone Mod {gravestone@1.16.3-1.0.2 DONE}
		Clumps-6.0.0.11.jar Clumps {clumps@6.0.0.11 DONE}
		shutupexperimentalsettings-1.0.1.jar Shutup Experimental Settings! {shutupexperimentalsettings@1.0.1 DONE}
		lava-monster-1.16.3-1.0.9.jar Lava Monster {lava_monster@1.0.9 DONE}
		JRFTL+[1.16.3]-1.1.jar JRFTL {jrftl@1.1 DONE}
		AutoRegLib-1.6-46.jar AutoRegLib {autoreglib@1.6-46 DONE}
		backpacked-1.6.1-1.16.3.jar Backpacked {backpacked@1.6.1 DONE}
		backpacker-1.0.0-1.16.3.jar Backpacker {backpacker@1.0.0 DONE}
		illagersweararmor-1.0.2.jar Illagers Wear Armor {illagersweararmor@1.0.2 DONE}
		Gobber2-1.16.3-2.3.17.jar Gobber 2 {gobber2@2.3.16 DONE}
		DungeonCrawl-1.16.3-2.1.1.jar Dungeon Crawl {dungeoncrawl@2.1.1 DONE}
		MutantBeasts-1.16.3-1.1.2.jar Mutant Beasts {mutantbeasts@1.16.3-1.1.2 DONE}
		guardvillagers-1.16.3-1.1.5.jar Guard Villagers {guardvillagers@1.1.5 DONE}
		LightingWand-1.16.2-1.7.0.jar Lighting Wand {lightingwand@1.7.0 DONE}
		travellersboots-1.16.x-1.4.3.jar Traveller's Boots {travellersboots@1.4.3 DONE}
		PickUpNotifier-v1.2-1.16.3.jar Pick Up Notifier {pickupnotifier@1.2 DONE}
		mahoutsukai-1.16.3-v1.25.1.jar Mahou Tsukai {mahoutsukai@1.16.3-v1.25.1 DONE}
		Hwyla-forge-1.10.11-B78_1.16.2.jar Waila {waila@1.10.11-B78_1.16.2 DONE}
		BackTools-1.16.3-10.0.0.jar Back Tools {backtools@10.0.0 DONE}
		iChunUtil-1.16.3-10.0.0.jar iChunUtil {ichunutil@10.0.0 DONE}
		forge-1.16.3-34.1.0-universal.jar Forge {forge@34.1.0 DONE}
		Quark-r2.4-272.jar Quark {quark@r2.4-272 DONE}
		SoundFilters-0.14_for_1.16.2.jar Sound Filters {soundfilters@0.14_for_1.16.2 DONE}
		BetterMineshaftsForge-1.16.2-1.0.1.jar YUNG's Better Mineshafts {bettermineshafts@1.16.2-1.0.1 DONE}
		dash-1.16.3-1.0.1.jar Dash {dash@1.0.1 DONE}
		TrinityWeapons-1.16.2-1.5.0 (1).jar TrinityWeapons {trinity@1.5.0 DONE}
		infernalmobs-1.16.2.1.jar Infernal Mobs {infernalmobs@1.16.2.1 DONE}
		dungeons_gear-1.16.2+1.16.3-2.0.11.jar Dungeons Gear {dungeons_gear@2.0.11 DONE}
		xptome-1.16.2-v1.1.6.jar XP Tome {xpbook@v1.1.6 DONE}
	Patchouli open book context: n/a
	Player Count: 1 / 8; [ServerPlayerEntity['sim37546'/7, l='ServerLevel[New World]', x=9.09, y=4.00, z=212.06]]
	Data Packs: vanilla, mod:repurposed_structures, mod:thirdpersonelytra (incompatible), mod:elenaidodge, mod:spiderstpo, mod:dogslie, mod:goblintraders, mod:torohealth (incompatible), mod:strawgolem, mod:curios, mod:botania, mod:patchouli (incompatible), mod:bettercaves (incompatible), mod:xaerominimap, mod:waystones (incompatible), mod:gravestone, mod:clumps (incompatible), mod:shutupexperimentalsettings (incompatible), mod:lava_monster (incompatible), mod:jrftl (incompatible), mod:autoreglib (incompatible), mod:backpacked (incompatible), mod:backpacker, mod:illagersweararmor (incompatible), mod:gobber2 (incompatible), mod:dungeoncrawl, mod:mutantbeasts (incompatible), mod:guardvillagers (incompatible), mod:lightingwand, mod:travellersboots (incompatible), mod:pickupnotifier (incompatible), mod:mahoutsukai (incompatible), mod:waila, mod:backtools, mod:ichunutil, mod:forge, mod:soundfilters (incompatible), mod:bettermineshafts (incompatible), mod:dash (incompatible), mod:trinity (incompatible), mod:infernalmobs (incompatible), mod:dungeons_gear, mod:xpbook, mod:quark (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.3_HD_U_G3
	OptiFine Build: 20200916-082411
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.4.0 - Build 20.19.15.4835
	OpenGlRenderer: Intel(R) HD Graphics 5500
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by Thelnfamous1** [comment]
Seems like a method with private access is being called rather than one with public access. Will be fixed in next update.
