### ISSUE TITLE
Pekhui Incompatibility 

### ISSUE THREAD

**Issue by Pineappleguy03** [Thelnfamous1/Dungeons-Gear#59]
[01May2021 18:31:12.255] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Pineappleguy03, --version, 1.16.5-forge-36.1.13, --gameDir, C:\games\.minecraft, --assetsDir, C:\games\.minecraft\assets, --assetIndex, 1.16, --uuid, ec6c9d897ef74f078d21233bdce5e774, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.1.13, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[01May2021 18:31:12.259] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_51 by Oracle Corporation
[01May2021 18:31:12.279] [main/WARN] [cpw.mods.modlauncher.SecureJarHandler/]: LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED
[01May2021 18:31:12.443] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[01May2021 18:31:12.445] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFine ZIP file: C:\games\.minecraft\mods\OptiFine_1.16.5_HD_U_G7.jar
[01May2021 18:31:12.447] [main/INFO] [optifine.OptiFineTransformer/]: Target.PRE_CLASS is available
[01May2021 18:31:12.552] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[01May2021 18:31:12.599] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/games/.minecraft/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[01May2021 18:31:12.608] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[01May2021 18:31:14.833] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'
[01May2021 18:31:14.873] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[01May2021 18:31:14.922] [main/INFO] [optifine.OptiFineTransformer/]: Targets: 308
[01May2021 18:31:15.558] [main/INFO] [optifine.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
[01May2021 18:31:15.736] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.16.5-forge-36.1.13, --gameDir, C:\games\.minecraft, --assetsDir, C:\games\.minecraft\assets, --uuid, ec6c9d897ef74f078d21233bdce5e774, --username, Pineappleguy03, --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, release]
[01May2021 18:31:20.749] [main/WARN] [mixin/]: @ModifyConstant conflict. Skipping dungeons_gear.mixins.json:PlayerEntityMixin->@ModifyConstant::getAttackReachSquared(D)D with priority 1000, already redirected by pehkui.mixins.json:reach.PlayerEntityMixin->@ModifyConstant::attackModifyDistance(D)D with priority 1000
[01May2021 18:31:20.751] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[01May2021 18:31:20.752] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[01May2021 18:31:20.752] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[01May2021 18:31:20.752] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[01May2021 18:31:20.752] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[01May2021 18:31:20.752] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[01May2021 18:31:20.752] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[01May2021 18:31:20.753] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01May2021 18:31:20.753] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01May2021 18:31:20.753] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01May2021 18:31:20.753] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[01May2021 18:31:20.753] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[01May2021 18:31:20.754] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$459/615830852.call(Unknown Source)
[01May2021 18:31:20.754] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[01May2021 18:31:20.754] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[01May2021 18:31:20.754] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[01May2021 18:31:20.754] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[01May2021 18:31:20.755] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
[01May2021 18:31:20.755] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
[01May2021 18:31:20.755] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
[01May2021 18:31:20.755] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[01May2021 18:31:20.755] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[01May2021 18:31:20.755] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[01May2021 18:31:20.755] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[01May2021 18:31:20.756] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[01May2021 18:31:20.756] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[01May2021 18:31:20.756] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[01May2021 18:31:20.756] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[01May2021 18:31:20.756] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[01May2021 18:31:20.756] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138)
[01May2021 18:31:20.756] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[01May2021 18:31:20.756] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[01May2021 18:31:20.757] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:267)
[01May2021 18:31:20.757] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:101)
[01May2021 18:31:20.757] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
[01May2021 18:31:20.757] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.crash.CrashReport.func_230188_h_(CrashReport.java:425)
[01May2021 18:31:20.757] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.client.main.Main.main(Main.java:122)
[01May2021 18:31:20.757] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	... 11 more
[01May2021 18:31:20.757] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method getAttackReachSquared(D)D in dungeons_gear.mixins.json:PlayerEntityMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap dungeons_gear.refmap.json
[01May2021 18:31:20.758] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
[01May2021 18:31:20.758] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
[01May2021 18:31:20.758] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[01May2021 18:31:20.758] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[01May2021 18:31:20.758] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[01May2021 18:31:20.758] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[01May2021 18:31:20.758] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[01May2021 18:31:20.759] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[01May2021 18:31:20.759] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	... 31 more

**Comment by WenXin20** [comment]
Yes, I've noticed this as well. I'm using Forge v36.1.9, Pehkui v2.0.0, & Dungeons Gear v3.0.6.

I've reported it to Virtuoel/Pehkui#91 as well.

**Comment by Thelnfamous1** [comment]
Likely won't be fixed anytime soon, we both are modifying vanilla's hardcoded attack reach of 3 blocks to a modifiable attribute. Best case scenario, Forge adds a standardized attack reach attribute that makes everyone mixing into the same spot to do the same thing avoidable

**Comment by Jackiecrazy** [comment]
this should be fixed in the latest version.

**Comment by Jackiecrazy** [comment]
Nope, didn't work.

**Comment by Jackiecrazy** [comment]
fixed for real this time.

**Comment by WenXin20** [comment]
Thanks!
